[project]
name = "bookclub-local-poc"
version = "0.0.1"
description = "A tool that turns technical PDFs into flashcards and spaced-repetition decks — powered by LLM + retrieval — to help engineers retain and apply what they read."
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "httpx==0.27.0", # for HTTP requests
    "pydantic==2.8.0", # for data validation
    "fastapi==0.119.0", # for the web server
    "rich==13.7.0", # for progress bars!
    "prometheus-client==0.21.0", # for metrics
    "opentelemetry-sdk==1.38.0", # for tracing
    "opentelemetry-exporter-otlp-proto-http==1.38.0", # for exporting traces to tempo
    "opentelemetry-instrumentation-fastapi==0.59b0", # for tracing FastAPI
    "opentelemetry-instrumentation-requests==0.59b0", # for tracing HTTP requests
    "opentelemetry-instrumentation-logging==0.59b0", # for tracing logging
    "python-multipart>=0.0.9", # for file uploads
]

[dependency-groups]
dev = [
    "requests==2.32.5", # for HTTP requests
    "mypy==1.11.0", # for type checking
    "pre-commit==3.7.0", # for code quality
    "pytest==8.2.0", # for testing
    "pytest-asyncio==0.23.8", # for async testing
    "pytest-cov==5.0.0", # for coverage reporting
    "pytest-xdist==3.8.0", # for parallel testing
    "ruff==0.13.3", # for code quality
]

[tool.pytest.ini_options]
addopts = "--verbose -n auto --dist loadfile"
markers = [
    "long: mark test as a long running test, those test by the default should be run on ci/cd and are just inconveninet to run on local but still important",
    "behaviour: mark test as a behaviour test",
    "integration: mark test as an integration test",
    "e2e: mark test as an end-to-end test",
    "serial: mark test to run serially within same file (enforced by --dist loadfile)",
    "test_type(name): categorise tests by type (unit, integration, e2e)",
    "expected_duration(name): expected runtime bucket (short, medium, long)",
]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
